site_name: NOMANA-IT - Documentation, Blog and Resources
site_url: https://docs.nomana-it.fr

theme:
  name: material
  logo: assets/logo_ly.png
  favicon: assets/logo_ly.png
  custom_dir: overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: blue grey
      accent: amber
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: blue grey
      accent: amber
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode   
  features:
    - content.code.copy     
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tabs
    - navigation.path
    - navigation.top
    - navigation.footer
    - header.autohide
    - content.tooltips
nav:
  - Home: index.md
  - Liberty:
      - Getting Started: liberty/getting-started.md
      - Installation: 
        - Architecture: liberty/technical/architecture.md
        - Docker Installation Guide: liberty/technical/installation.md
        - Installation Tools Deployment Guide: liberty/technical/tools-deployment.md
        - Liberty Deployment Guide: liberty/technical/liberty-deployment.md
        - Create Linux Services: liberty/technical/linux-services.md
        - Enable SSL with Traefik: liberty/technical/post-ssl.md
      - Nomasx-1:
          - Administrator's Guide: 
            - Global Settings: liberty/nomasx1/admin/global-settings.md   
      - Core:
        - Getting Started: liberty/core/getting-started.md
        - New Project: liberty/core/new-project.md
        - Services:
          - AppProvider: liberty/core/services/appprovider.md
          - Modules: liberty/core/services/modules.md
          - Applications: liberty/core/services/applications.md
          - Users: liberty/core/services/users.md
          - Authentication: liberty/core/services/authentication.md
          - Use Media Query: liberty/core/services/use-media-query.md
          - Themes: liberty/core/services/themes.md
          - Error Boundary: liberty/core/services/error-boundary.md
          - Translations: liberty/core/services/translations.md
        - Core Components:
          - UI Elements: 
            - Alert: liberty/core/components/ui-elements/alert.md
            - AlertMessage: liberty/core/components/ui-elements/alert-message.md
            - Button: liberty/core/components/ui-elements/button.md
            - Card: liberty/core/components/ui-elements/card.md
      - API Documentation: liberty/api/liberty-api.md
      - Release Notes: liberty/release-notes.md
      - Issues: liberty/issues.md
      - Incidents: liberty/incidents.md        
  - API:
      - Getting Started: api/getting-started.md
      - JD Edwards API: 
        - Export XML source or PDF Output from JD Edwards BLOB fields: api/jde-api/jdebip.md        
        - Export source code for BSFN from JD Edwards BLOB field (F98780R): api/jde-api/jdebsfn.md        
      - BI Publisher API: 
        - Simple java class to encode string and display barcode 128 with BI Publisher RTF template: api/bip-api/nomabc.md        
        - Java package with Oracle BI Publisher API: api/bip-api/nomabip.md        
  - Blog:
    - blog/index.md
plugins:
  - search
  - awesome-pages
  - minify  
  - blog:
      blog_toc: true
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/fblettner
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/franck-blettner-72509510/          
  meta:
      - name: Content-Security-Policy
        value: frame-ancestors 'self' https://giscus.app;      
  consent:
    title: Cookie consent
    actions:
      - accept
      - manage
      - reject
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.           
markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
extra_css:
  - css/custom.css
extra_javascript:
  - js/extra.js  
copyright: >
  Copyright &copy; 2024 Nomana-IT –
  <a href="#__consent">Change cookie settings</a>
