import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  libertySidebar: [
    'liberty/getting-started',
    {
      type: 'category',
      label: 'Installation',
      link: {type: 'generated-index', slug: '/liberty/installation', description: 'Install and configure the Liberty Framework stack: Docker, Traefik, SSL and Linux services.'},
      items: [
        'liberty/technical/architecture',
        'liberty/technical/installation',
        'liberty/technical/tools-deployment',
        'liberty/technical/liberty-deployment',
        'liberty/technical/linux-services',
        'liberty/technical/post-ssl',
      ],
    },
    {
      type: 'category',
      label: 'Nomasx-1',
      link: {type: 'generated-index', slug: '/liberty/nomasx-1', description: 'Nomasx-1 — administration guides for the Liberty platform.'},
      items: [
        {
          type: 'category',
          label: "Administrator's Guide",
          link: {type: 'generated-index', description: 'Administrator-level configuration of Nomasx-1.'},
          items: ['liberty/nomasx1/admin/global-settings'],
        },
      ],
    },
    {
      type: 'category',
      label: 'React Components',
      link: {type: 'generated-index', slug: '/liberty/react-components', description: 'Liberty Core — modular React components, services, theming and main building blocks.'},
      items: [
        'liberty/core/getting-started',
        'liberty/core/new-project',
        {
          type: 'category',
          label: 'Services',
          link: {type: 'generated-index', description: 'Liberty Core services: providers, modules, applications, users, authentication, themes, translations.'},
          items: [
            'liberty/core/services/appprovider',
            'liberty/core/services/modules',
            'liberty/core/services/applications',
            'liberty/core/services/users',
            'liberty/core/services/authentication',
            'liberty/core/services/use-media-query',
            'liberty/core/services/themes',
            'liberty/core/services/error-boundary',
            'liberty/core/services/translations',
          ],
        },
        {
          type: 'category',
          label: 'Core Components',
          link: {type: 'generated-index', description: 'Reusable component groups: UI elements, inputs, dialogs, tables, charts.'},
          items: [
            {
              type: 'category',
              label: 'UI Elements',
              link: {type: 'generated-index', description: 'Buttons, alerts, cards, typography and other base UI elements.'},
              items: [
                'liberty/core/components/ui-elements/alert',
                'liberty/core/components/ui-elements/alert-message',
                'liberty/core/components/ui-elements/button',
                'liberty/core/components/ui-elements/card',
                'liberty/core/components/ui-elements/checkbox',
                'liberty/core/components/ui-elements/circular-progress',
                'liberty/core/components/ui-elements/collapse',
                'liberty/core/components/ui-elements/divider',
                'liberty/core/components/ui-elements/flex',
                'liberty/core/components/ui-elements/flex-advanced',
                'liberty/core/components/ui-elements/icon-button',
                'liberty/core/components/ui-elements/loading-indicator',
                'liberty/core/components/ui-elements/markdown',
                'liberty/core/components/ui-elements/snack-message',
                'liberty/core/components/ui-elements/toggle-button',
                'liberty/core/components/ui-elements/tooltip',
                'liberty/core/components/ui-elements/typography',
              ],
            },
            {
              type: 'category',
              label: 'Inputs & Forms',
              link: {type: 'generated-index', description: 'Form inputs: text, select, date picker, file upload, color picker.'},
              items: [
                'liberty/core/components/inputs-forms/checkbox',
                'liberty/core/components/inputs-forms/color-picker',
                'liberty/core/components/inputs-forms/date-picker',
                'liberty/core/components/inputs-forms/enum',
                'liberty/core/components/inputs-forms/file-upload',
                'liberty/core/components/inputs-forms/input',
                'liberty/core/components/inputs-forms/select',
              ],
            },
            {
              type: 'category',
              label: 'Dialogs & Overlays',
              link: {type: 'generated-index', description: 'Dialogs, confirmations, poppers, exports and tabbed overlays.'},
              items: [
                'liberty/core/components/dialogs-overlays/dialog',
                'liberty/core/components/dialogs-overlays/confirmation',
                'liberty/core/components/dialogs-overlays/export',
                'liberty/core/components/dialogs-overlays/popper',
                'liberty/core/components/dialogs-overlays/tabs',
              ],
            },
            {
              type: 'category',
              label: 'Tables & Lists',
              link: {type: 'generated-index', description: 'Data tables, grids, lists, trees and contextual menus.'},
              items: [
                'liberty/core/components/tables-lists/grid',
                'liberty/core/components/tables-lists/table',
                'liberty/core/components/tables-lists/list',
                'liberty/core/components/tables-lists/context-menus',
                'liberty/core/components/tables-lists/tree',
              ],
            },
            {
              type: 'category',
              label: 'Charts',
              link: {type: 'generated-index', description: 'Bar, line and pie chart components.'},
              items: [
                'liberty/core/components/charts/bar',
                'liberty/core/components/charts/line',
                'liberty/core/components/charts/pie',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Main Components',
          link: {type: 'generated-index', description: 'High-level layout components: Header, Content, Login, Menus, Users.'},
          items: [
            'liberty/core/components/main-components/header',
            'liberty/core/components/main-components/content',
            'liberty/core/components/main-components/login',
            'liberty/core/components/main-components/menus',
            'liberty/core/components/main-components/users',
          ],
        },
        {
          type: 'category',
          label: 'Forms Components',
          link: {type: 'generated-index', description: 'Composite form components: Dashboard and Advanced Grid.'},
          items: [
            'liberty/core/components/forms-components/dashboard',
            'liberty/core/components/forms-components/advanced-grid',
          ],
        },
        {
          type: 'category',
          label: 'Styled Elements',
          link: {type: 'generated-index', description: 'Theme-aware styled primitives used throughout Liberty Core.'},
          items: [
            'liberty/core/components/styled-elements/button',
            'liberty/core/components/styled-elements/card',
            'liberty/core/components/styled-elements/dialog',
            'liberty/core/components/styled-elements/div',
            'liberty/core/components/styled-elements/form',
            'liberty/core/components/styled-elements/global-styles',
            'liberty/core/components/styled-elements/icon-button',
            'liberty/core/components/styled-elements/icons',
            'liberty/core/components/styled-elements/input',
            'liberty/core/components/styled-elements/list',
            'liberty/core/components/styled-elements/main',
            'liberty/core/components/styled-elements/menus',
            'liberty/core/components/styled-elements/paper',
            'liberty/core/components/styled-elements/stack',
            'liberty/core/components/styled-elements/table',
            'liberty/core/components/styled-elements/tabs',
            'liberty/core/components/styled-elements/typography',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      link: {type: 'generated-index', slug: '/liberty/reference', description: 'API reference, release notes, known issues and incident history.'},
      items: [
        'liberty/api/liberty-api',
        'liberty/release-notes',
        'liberty/issues',
        'liberty/incidents',
      ],
    },
  ],

  nomaublSidebar: [
    'nomaubl/getting-started',
    {
      type: 'category',
      label: 'Application',
      link: {type: 'generated-index', slug: '/nomaubl/application', description: 'Main app navigation: dashboard, invoices, e-reporting, e-directory, integration errors and AI capabilities.'},
      items: [
        'nomaubl/application/dashboard',
        'nomaubl/application/invoices',
        'nomaubl/application/ereporting',
        'nomaubl/application/edirectory',
        'nomaubl/application/integration-errors',
        'nomaubl/application/ai-capabilities',
      ],
    },
    {
      type: 'category',
      label: 'Sync',
      link: {type: 'generated-index', slug: '/nomaubl/sync', description: 'Inbound/outbound synchronisation: fetch input, import and retrieve statuses.'},
      items: [
        'nomaubl/sync/fetch-input',
        'nomaubl/sync/import',
        'nomaubl/sync/retrieve-statuses',
      ],
    },
    {
      type: 'category',
      label: 'Processing',
      link: {type: 'generated-index', slug: '/nomaubl/processing', description: 'Single document-processing entry point (XML or UBL, selected by the template), the chained Extract and Process flow, and the API connector tester.'},
      items: [
        'nomaubl/processing/document',
        'nomaubl/processing/extract-and-process',
        'nomaubl/processing/process-api',
      ],
    },
    {
      type: 'category',
      label: 'UBL Tools',
      link: {type: 'generated-index', slug: '/nomaubl/ubl-tools', description: 'Validate, edit and inspect UBL/XML; manage UBL defaults.'},
      items: [
        'nomaubl/ubl-tools/validate',
        'nomaubl/ubl-tools/xsl-editor',
        'nomaubl/ubl-tools/xml-viewer',
        {
          type: 'category',
          label: 'UBL Defaults',
          link: {type: 'generated-index', slug: '/nomaubl/ubl-tools/ubl-defaults', description: 'Default values applied to generated UBL documents and how to override them per template.'},
          items: [
            'nomaubl/ubl-tools/ubl-defaults/overview',
            'nomaubl/ubl-tools/ubl-defaults/ubl-header-defaults',
            'nomaubl/ubl-tools/ubl-defaults/scheme-ids',
            'nomaubl/ubl-tools/ubl-defaults/invoice-type',
            'nomaubl/ubl-tools/ubl-defaults/business-process-type',
            'nomaubl/ubl-tools/ubl-defaults/payment-code-mapping',
            'nomaubl/ubl-tools/ubl-defaults/unit-of-measure-mapping',
            'nomaubl/ubl-tools/ubl-defaults/currency-code-mapping',
            'nomaubl/ubl-tools/ubl-defaults/document-type-bar-routing',
            'nomaubl/ubl-tools/ubl-defaults/vat-categories',
            'nomaubl/ubl-tools/ubl-defaults/suppliers-companies',
            'nomaubl/ubl-tools/ubl-defaults/french-legal-notes',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Extract',
      link: {type: 'generated-index', slug: '/nomaubl/extract', description: 'Source extraction channels: archive directories, FTP/SFTP servers and JD Edwards BIP Print Queue.'},
      items: [
        'nomaubl/extract/extract-archive',
        'nomaubl/extract/extract-ftp',
        'nomaubl/extract/extract-bip',
      ],
    },
    {
      type: 'category',
      label: 'Management',
      link: {type: 'generated-index', slug: '/nomaubl/management', description: 'Operational management: document templates, PDF templates, notifications and notification rules, file versions, processing log and the command-line interface.'},
      items: [
        'nomaubl/management/documents',
        'nomaubl/management/pdf-templates',
        'nomaubl/management/notifications',
        'nomaubl/management/notification-rules',
        'nomaubl/management/file-versions',
        'nomaubl/management/processing-log',
        'nomaubl/management/command-line',
      ],
    },
    {
      type: 'category',
      label: 'Configuration',
      link: {type: 'generated-index', slug: '/nomaubl/configuration', description: 'Application-wide configuration: system parameters, reference lists, connectors and security.'},
      items: [
        {
          type: 'category',
          label: 'System',
          link: {type: 'generated-index', slug: '/nomaubl/configuration/system', description: 'System-level parameters: e-directory, e-invoicing, fetch invoices, document types and statuses.'},
          items: [
            'nomaubl/configuration/system/edirectory',
            'nomaubl/configuration/system/einvoicing',
            'nomaubl/configuration/system/fetch-invoices',
            'nomaubl/configuration/system/global',
            'nomaubl/configuration/system/document-types',
            'nomaubl/configuration/system/statuses',
          ],
        },
        'nomaubl/configuration/reference-lists',
        'nomaubl/configuration/api-connectors',
        {
          type: 'category',
          label: 'Database Connectors',
          link: {type: 'generated-index', slug: '/nomaubl/configuration/database-connectors', description: 'Database connection settings for NomaUBL and JD Edwards.'},
          items: [
            'nomaubl/configuration/database-connectors/nomaubl',
            'nomaubl/configuration/database-connectors/jdedwards',
          ],
        },
        'nomaubl/configuration/ftp-connectors',
        {
          type: 'category',
          label: 'Security',
          link: {type: 'generated-index', slug: '/nomaubl/configuration/security', description: 'Users and roles management.'},
          items: [
            'nomaubl/configuration/security/users',
            'nomaubl/configuration/security/roles',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'References',
      link: {type: 'generated-index', slug: '/nomaubl/references', description: 'Reference docs surfaced inside the app: status codes, reason codes, UBL semantics, database schema and HTTP API.'},
      items: [
        'nomaubl/references/status-reference',
        'nomaubl/references/reason-codes',
        'nomaubl/references/ubl-reference',
        'nomaubl/references/database-tables',
        {
          type: 'link',
          label: 'API Reference',
          href: '/nomaubl/api-reference/',
        },
      ],
    },
    'nomaubl/release-notes',
  ],

  apiSidebar: [
    'api/getting-started',
    {
      type: 'category',
      label: 'JD Edwards API',
      link: {type: 'generated-index', slug: '/api/jd-edwards-api', description: 'Java packages for JD Edwards integration: BLOB exports for BI Publisher and BSFN source code.'},
      items: [
        'api/jde-api/jdebip',
        'api/jde-api/jdebsfn',
      ],
    },
    {
      type: 'category',
      label: 'BI Publisher API',
      link: {type: 'generated-index', slug: '/api/bi-publisher-api', description: 'BI Publisher integration utilities: Code 128 barcodes and the NOMABIP wrapper API.'},
      items: [
        'api/bip-api/nomabc',
        'api/bip-api/nomabip',
      ],
    },
  ],
};

export default sidebars;
