import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  libertySidebar: [
    'liberty/getting-started',
    {
      type: 'category',
      label: 'Framework',
      link: {type: 'generated-index', slug: '/liberty/framework', description: 'Liberty Framework — a connector-driven low-code platform for internal apps, admin tools and BI dashboards. Read the overview, then walk through one of the tutorials to build a real app end-to-end.'},
      items: [
        'liberty/framework/overview',
        'liberty/framework/what-you-can-build',
        {
          type: 'category',
          label: 'Getting Started',
          link: {type: 'generated-index', slug: '/liberty/framework/getting-started', description: 'Installation, first app walkthrough and project layout.'},
          items: [
            'liberty/framework/getting-started/installation',
            'liberty/framework/getting-started/first-app',
            'liberty/framework/getting-started/project-layout',
          ],
        },
        {
          type: 'category',
          label: 'Tutorial — Build a CRM',
          link: {type: 'generated-index', slug: '/liberty/framework/tutorial-crm', description: 'A six-step walkthrough that builds a working CRM end-to-end: customers, deals and activities, with a pipeline dashboard, OIDC sign-in, the AI assistant and a scheduled job.'},
          items: [
            'liberty/framework/tutorial-crm/setup',
            'liberty/framework/tutorial-crm/customers',
            'liberty/framework/tutorial-crm/deals',
            'liberty/framework/tutorial-crm/dashboard',
            'liberty/framework/tutorial-crm/auth',
            'liberty/framework/tutorial-crm/ai-and-jobs',
          ],
        },
        {
          type: 'category',
          label: 'Configuration',
          link: {type: 'generated-index', slug: '/liberty/framework/configuration', description: 'Settings UI, app.toml, environment variables, hot-reload and encrypted secrets.'},
          items: [
            'liberty/framework/configuration/settings-ui',
            'liberty/framework/configuration/app-toml',
            'liberty/framework/configuration/environment-variables',
            'liberty/framework/configuration/hot-reload',
            'liberty/framework/configuration/encryption-secrets',
          ],
        },
        {
          type: 'category',
          label: 'Build an application',
          link: {type: 'generated-index', slug: '/liberty/framework/build', description: 'Task-oriented "how do I…" pages — create queries, screens, menus, applications and secure them. Pair with the Concepts section for the deep reference behind each task.'},
          items: [
            {
              type: 'category',
              label: 'Queries',
              link: {type: 'generated-index', slug: '/liberty/framework/build/queries', description: 'Everything you do on the Connectors page — add a query from a real table, write a custom one, clone, scaffold sequences and lookups, bind parameters, ship per-dialect variants.'},
              items: [
                'liberty/framework/build/queries/overview',
                'liberty/framework/build/queries/create-from-database',
                'liberty/framework/build/queries/create-custom',
                'liberty/framework/build/queries/clone',
                'liberty/framework/build/queries/sequences-and-lookups',
                'liberty/framework/build/queries/parameter-binding',
                'liberty/framework/build/queries/per-dialect-sql',
              ],
            },
            {
              type: 'category',
              label: 'Screens',
              link: {type: 'generated-index', slug: '/liberty/framework/build/screens', description: 'Everything you do in the Screen Designer — wire a screen to a query, configure columns, build the dialog visually, add conditional fields, wire actions and lifecycle hooks, embed nested tabs.'},
              items: [
                'liberty/framework/build/screens/overview',
                'liberty/framework/build/screens/create-from-query',
                'liberty/framework/build/screens/columns',
                'liberty/framework/build/screens/dialog-builder',
                'liberty/framework/build/screens/conditional-fields',
                'liberty/framework/build/screens/actions-and-lifecycle',
                'liberty/framework/build/screens/nested-tabs',
              ],
            },
            {
              type: 'category',
              label: 'Menus',
              link: {type: 'generated-index', slug: '/liberty/framework/build/menus', description: 'The Menus page — register a connector as an app in the top switcher, build the navigation tree (folders + leaves), pick the right leaf type (query / endpoint / dashboard / page), gate by roles, translate labels and pick icons.'},
              items: [
                'liberty/framework/build/menus/overview',
                'liberty/framework/build/menus/make-connector-an-app',
                'liberty/framework/build/menus/build-the-tree',
                'liberty/framework/build/menus/item-types',
                'liberty/framework/build/menus/permissions-and-roles',
                'liberty/framework/build/menus/translations-and-icons',
              ],
            },
            {
              type: 'category',
              label: 'Secure',
              link: {type: 'generated-index', slug: '/liberty/framework/build/secure', description: 'Identity + authorization + at-rest secret protection. The two identity backends (local TOML / DB), OIDC layered on top, role/permission composition with allow/deny grammar, the AccessBuilder page, encrypted secrets, license key.'},
              items: [
                'liberty/framework/build/secure/overview',
                'liberty/framework/build/secure/sign-in',
                'liberty/framework/build/secure/roles-and-permissions',
                'liberty/framework/build/secure/users',
                'liberty/framework/build/secure/encrypted-secrets',
                'liberty/framework/build/secure/license-key',
              ],
            },
            {
              type: 'category',
              label: 'Plugins',
              link: {type: 'generated-index', slug: '/liberty/framework/build/plugins', description: 'Custom Python that lives in the apps repo and is imported by the framework at startup. The escape hatch when declarative steps don\'t fit — function contract, ETL primitives toolkit, deploy and debug.'},
              items: [
                'liberty/framework/build/plugins/overview',
                'liberty/framework/build/plugins/write-a-callable',
                'liberty/framework/build/plugins/etl-primitives',
                'liberty/framework/build/plugins/deploy-and-debug',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Concepts',
          link: {type: 'generated-index', slug: '/liberty/framework/concepts', description: 'Deep reference behind the Build pages — connectors, dictionary, dashboards, charts and form-condition expressions.'},
          items: [
            'liberty/framework/connectors',
            'liberty/framework/dictionary',
            'liberty/framework/dashboards',
            'liberty/framework/charts',
            'liberty/framework/form-conditions',
          ],
        },
        {
          type: 'category',
          label: 'Apps & Plugins',
          link: {type: 'generated-index', slug: '/liberty/framework/apps', description: 'How a Liberty app is structured, custom Python plugins and internationalization.'},
          items: [
            'liberty/framework/apps/overview',
            'liberty/framework/apps/plugins',
            'liberty/framework/apps/i18n',
          ],
        },
        'liberty/framework/ai-assistant',
        {
          type: 'category',
          label: 'Cookbook',
          link: {type: 'generated-index', slug: '/liberty/framework/cookbook', description: 'Short recipes for common patterns — Excel export, file upload, OIDC sign-in, audit trail, bulk import, scheduled report, row-level access, AI exposure.'},
          items: [
            'liberty/framework/cookbook/crud-existing-table',
            'liberty/framework/cookbook/excel-export',
            'liberty/framework/cookbook/file-upload',
            'liberty/framework/cookbook/audit-trail',
            'liberty/framework/cookbook/bulk-import',
            'liberty/framework/cookbook/multi-step-form',
            'liberty/framework/cookbook/oidc-sso',
            'liberty/framework/cookbook/scheduled-report-email',
            'liberty/framework/cookbook/expose-to-ai',
            'liberty/framework/cookbook/row-level-access',
          ],
        },
        'liberty/framework/cli-reference',
        'liberty/framework/rest-api',
        {
          type: 'category',
          label: 'Deployment',
          link: {type: 'generated-index', slug: '/liberty/framework/deployment', description: 'Running Liberty in production and moving between versions.'},
          items: [
            'liberty/framework/deployment/running-production',
            'liberty/framework/deployment/upgrading',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Archive — v1 Installation (Docker stack)',
      link: {type: 'generated-index', slug: '/liberty/archive/installation', description: 'Legacy installation pages for the v1 Docker stack. Retained while the v1 → Liberty Next migration is in progress; new Liberty Next installation docs will replace this section once Docker support for Liberty Next ships.'},
      items: [
        'liberty/technical/architecture',
        'liberty/technical/installation',
        'liberty/technical/tools-deployment',
        'liberty/technical/liberty-deployment',
        'liberty/technical/linux-services',
        'liberty/technical/post-ssl',
      ],
    },
    {
      type: 'category',
      label: 'Archive — v1 React Components',
      link: {type: 'generated-index', slug: '/liberty/archive/react-components', description: 'Legacy reference for the v1 React component library (Liberty Core). Retained while the v1 → Liberty Next migration is in progress and will be retired at the end of the migration.'},
      items: [
        'liberty/core/getting-started',
        'liberty/core/new-project',
        {
          type: 'category',
          label: 'Services',
          link: {type: 'generated-index', description: 'Liberty Core services: providers, modules, applications, users, authentication, themes, translations.'},
          items: [
            'liberty/core/services/appprovider',
            'liberty/core/services/modules',
            'liberty/core/services/applications',
            'liberty/core/services/users',
            'liberty/core/services/authentication',
            'liberty/core/services/use-media-query',
            'liberty/core/services/themes',
            'liberty/core/services/error-boundary',
            'liberty/core/services/translations',
          ],
        },
        {
          type: 'category',
          label: 'Core Components',
          link: {type: 'generated-index', description: 'Reusable component groups: UI elements, inputs, dialogs, tables, charts.'},
          items: [
            {
              type: 'category',
              label: 'UI Elements',
              link: {type: 'generated-index', description: 'Buttons, alerts, cards, typography and other base UI elements.'},
              items: [
                'liberty/core/components/ui-elements/alert',
                'liberty/core/components/ui-elements/alert-message',
                'liberty/core/components/ui-elements/button',
                'liberty/core/components/ui-elements/card',
                'liberty/core/components/ui-elements/checkbox',
                'liberty/core/components/ui-elements/circular-progress',
                'liberty/core/components/ui-elements/collapse',
                'liberty/core/components/ui-elements/divider',
                'liberty/core/components/ui-elements/flex',
                'liberty/core/components/ui-elements/flex-advanced',
                'liberty/core/components/ui-elements/icon-button',
                'liberty/core/components/ui-elements/loading-indicator',
                'liberty/core/components/ui-elements/markdown',
                'liberty/core/components/ui-elements/snack-message',
                'liberty/core/components/ui-elements/toggle-button',
                'liberty/core/components/ui-elements/tooltip',
                'liberty/core/components/ui-elements/typography',
              ],
            },
            {
              type: 'category',
              label: 'Inputs & Forms',
              link: {type: 'generated-index', description: 'Form inputs: text, select, date picker, file upload, color picker.'},
              items: [
                'liberty/core/components/inputs-forms/checkbox',
                'liberty/core/components/inputs-forms/color-picker',
                'liberty/core/components/inputs-forms/date-picker',
                'liberty/core/components/inputs-forms/enum',
                'liberty/core/components/inputs-forms/file-upload',
                'liberty/core/components/inputs-forms/input',
                'liberty/core/components/inputs-forms/select',
              ],
            },
            {
              type: 'category',
              label: 'Dialogs & Overlays',
              link: {type: 'generated-index', description: 'Dialogs, confirmations, poppers, exports and tabbed overlays.'},
              items: [
                'liberty/core/components/dialogs-overlays/dialog',
                'liberty/core/components/dialogs-overlays/confirmation',
                'liberty/core/components/dialogs-overlays/export',
                'liberty/core/components/dialogs-overlays/popper',
                'liberty/core/components/dialogs-overlays/tabs',
              ],
            },
            {
              type: 'category',
              label: 'Tables & Lists',
              link: {type: 'generated-index', description: 'Data tables, grids, lists, trees and contextual menus.'},
              items: [
                'liberty/core/components/tables-lists/grid',
                'liberty/core/components/tables-lists/table',
                'liberty/core/components/tables-lists/list',
                'liberty/core/components/tables-lists/context-menus',
                'liberty/core/components/tables-lists/tree',
              ],
            },
            {
              type: 'category',
              label: 'Charts',
              link: {type: 'generated-index', description: 'Bar, line and pie chart components.'},
              items: [
                'liberty/core/components/charts/bar',
                'liberty/core/components/charts/line',
                'liberty/core/components/charts/pie',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Main Components',
          link: {type: 'generated-index', description: 'High-level layout components: Header, Content, Login, Menus, Users.'},
          items: [
            'liberty/core/components/main-components/header',
            'liberty/core/components/main-components/content',
            'liberty/core/components/main-components/login',
            'liberty/core/components/main-components/menus',
            'liberty/core/components/main-components/users',
          ],
        },
        {
          type: 'category',
          label: 'Forms Components',
          link: {type: 'generated-index', description: 'Composite form components: Dashboard and Advanced Grid.'},
          items: [
            'liberty/core/components/forms-components/dashboard',
            'liberty/core/components/forms-components/advanced-grid',
          ],
        },
        {
          type: 'category',
          label: 'Styled Elements',
          link: {type: 'generated-index', description: 'Theme-aware styled primitives used throughout Liberty Core.'},
          items: [
            'liberty/core/components/styled-elements/button',
            'liberty/core/components/styled-elements/card',
            'liberty/core/components/styled-elements/dialog',
            'liberty/core/components/styled-elements/div',
            'liberty/core/components/styled-elements/form',
            'liberty/core/components/styled-elements/global-styles',
            'liberty/core/components/styled-elements/icon-button',
            'liberty/core/components/styled-elements/icons',
            'liberty/core/components/styled-elements/input',
            'liberty/core/components/styled-elements/list',
            'liberty/core/components/styled-elements/main',
            'liberty/core/components/styled-elements/menus',
            'liberty/core/components/styled-elements/paper',
            'liberty/core/components/styled-elements/stack',
            'liberty/core/components/styled-elements/table',
            'liberty/core/components/styled-elements/tabs',
            'liberty/core/components/styled-elements/typography',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      link: {type: 'generated-index', slug: '/liberty/reference', description: 'API reference, release notes, known issues and incident history.'},
      items: [
        'liberty/api/liberty-api',
        'liberty/release-notes',
        'liberty/issues',
        'liberty/incidents',
      ],
    },
  ],

  nomaflowSidebar: [
    'liberty/nomaflow/overview',
    'liberty/nomaflow/getting-started',
    'liberty/nomaflow/concepts',
    {
      type: 'category',
      label: 'Jobs',
      link: {type: 'generated-index', slug: '/liberty/nomaflow/jobs', description: 'The Jobs page — browse the catalogue, create or edit a workflow, schedule it.'},
      items: [
        'liberty/nomaflow/jobs/catalog',
        'liberty/nomaflow/jobs/create',
        'liberty/nomaflow/jobs/schedules',
      ],
    },
    'liberty/nomaflow/steps',
    {
      type: 'category',
      label: 'Runs',
      link: {type: 'generated-index', slug: '/liberty/nomaflow/runs', description: 'Run history, live monitoring, troubleshooting.'},
      items: [
        'liberty/nomaflow/runs/history',
        'liberty/nomaflow/runs/troubleshoot',
      ],
    },
    {
      type: 'category',
      label: 'Workflow recipes',
      link: {type: 'generated-index', slug: '/liberty/nomaflow/workflows', description: 'Ready-to-adapt patterns — scheduled DB sync, API pull, conditional cleanup.'},
      items: [
        'liberty/nomaflow/workflows/scheduled-sync',
        'liberty/nomaflow/workflows/api-pull',
        'liberty/nomaflow/workflows/conditional-cleanup',
      ],
    },
    {
      type: 'category',
      label: 'Customisation',
      link: {type: 'generated-index', slug: '/liberty/nomaflow/customisation', description: 'Extension points — custom Python steps and outbound notifications.'},
      items: [
        'liberty/nomaflow/custom-python',
        'liberty/nomaflow/notifications',
      ],
    },
    'liberty/nomaflow/administration',
  ],

  nomasx1Sidebar: [
    'liberty/nomasx1/overview',
    {
      type: 'category',
      label: 'Security',
      link: {type: 'generated-index', slug: '/liberty/nomasx-1/security', description: 'Security catalog: users, roles, assignments, gaps and duplicates.'},
      items: [
        'liberty/nomasx1/security/users',
        'liberty/nomasx1/security/roles',
        'liberty/nomasx1/security/assignments',
        'liberty/nomasx1/security/roles-not-used',
        'liberty/nomasx1/security/users-without-roles',
        'liberty/nomasx1/security/roles-matrix',
        'liberty/nomasx1/security/duplicate-users',
        'liberty/nomasx1/security/users-audit',
        {
          type: 'category',
          label: 'LDAP',
          link: {type: 'generated-index', slug: '/liberty/nomasx-1/security/ldap', description: 'Reconciliation with the corporate LDAP / Active Directory identity provider.'},
          items: [
            'liberty/nomasx1/security/ldap/users',
            'liberty/nomasx1/security/ldap/users-without-ad',
            'liberty/nomasx1/security/ldap/users-by-applications',
            'liberty/nomasx1/security/ldap/settings',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Applications',
      link: {type: 'generated-index', slug: '/liberty/nomasx-1/applications', description: 'Per-application views: menus, rights, conflicts, activity log and Object Usage Tracking.'},
      items: [
        'liberty/nomasx1/applications/menus',
        {
          type: 'category',
          label: 'Rights',
          link: {type: 'generated-index', slug: '/liberty/nomasx-1/applications/rights', description: 'Effective rights: by user, by role, by role + menu, by user + role + OUT.'},
          items: [
            'liberty/nomasx1/applications/rights/users',
            'liberty/nomasx1/applications/rights/roles',
            'liberty/nomasx1/applications/rights/users-roles',
            'liberty/nomasx1/applications/rights/users-menus',
            'liberty/nomasx1/applications/rights/roles-menus',
            'liberty/nomasx1/applications/rights/users-roles-out',
          ],
        },
        {
          type: 'category',
          label: 'Conflicts',
          link: {type: 'generated-index', slug: '/liberty/nomasx-1/applications/conflicts', description: 'Segregation-of-duties analysis: summary, details, proven, by user and by role pair.'},
          items: [
            'liberty/nomasx1/applications/conflicts/summary',
            'liberty/nomasx1/applications/conflicts/details',
            'liberty/nomasx1/applications/conflicts/proven',
            'liberty/nomasx1/applications/conflicts/users',
            'liberty/nomasx1/applications/conflicts/roles',
          ],
        },
        'liberty/nomasx1/applications/activity-log',
        {
          type: 'category',
          label: 'Object Usage Tracking',
          link: {type: 'generated-index', slug: '/liberty/nomasx-1/applications/out', description: 'Object Usage Tracking: components, details, users / roles and objects.'},
          items: [
            'liberty/nomasx1/applications/out/components',
            'liberty/nomasx1/applications/out/details',
            'liberty/nomasx1/applications/out/users-roles',
            'liberty/nomasx1/applications/out/objects',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Database',
      link: {type: 'generated-index', slug: '/liberty/nomasx-1/database', description: 'Database-level properties and audit trail.'},
      items: [
        'liberty/nomasx1/database/oracle',
        'liberty/nomasx1/database/audit-trail',
        'liberty/nomasx1/database/audit-lookup',
      ],
    },
    {
      type: 'category',
      label: 'Licenses',
      link: {type: 'generated-index', slug: '/liberty/nomasx-1/licenses', description: 'Licence management: CSI inventory, JD Edwards and Oracle reporting, subscribed quantities, usage and financial impact.'},
      items: [
        'liberty/nomasx1/licenses/csi',
        'liberty/nomasx1/licenses/jd-edwards',
        'liberty/nomasx1/licenses/oracle',
        'liberty/nomasx1/licenses/subscribed',
        'liberty/nomasx1/licenses/usage-report',
        'liberty/nomasx1/licenses/financial-report',
      ],
    },
    {
      type: 'category',
      label: 'Settings',
      link: {type: 'generated-index', slug: '/liberty/nomasx-1/settings', description: 'Configuration screens: applications, SoD framework, security flags, JDE classification, Oracle catalog and pricing.'},
      items: [
        {
          type: 'category',
          label: 'Global',
          link: {type: 'generated-index', slug: '/liberty/nomasx-1/settings/global', description: 'Global registry: applications and per-application custom SQL.'},
          items: [
            'liberty/nomasx1/settings/global/applications',
            'liberty/nomasx1/settings/global/custom-queries',
          ],
        },
        {
          type: 'category',
          label: 'Segregation of Duties',
          link: {type: 'generated-index', slug: '/liberty/nomasx-1/settings/sod', description: 'SoD framework: processes, activities, risks, matrix, objects.'},
          items: [
            'liberty/nomasx1/settings/sod/process',
            'liberty/nomasx1/settings/sod/activities',
            'liberty/nomasx1/settings/sod/risks',
            'liberty/nomasx1/settings/sod/matrix',
            'liberty/nomasx1/settings/sod/objects',
          ],
        },
        {
          type: 'category',
          label: 'User & AD flags',
          link: {type: 'generated-index', slug: '/liberty/nomasx-1/settings/user-flags', description: 'Per-user flags and AD department catalog.'},
          items: [
            'liberty/nomasx1/settings/security/users-properties',
            'liberty/nomasx1/settings/security/department',
          ],
        },
        {
          type: 'category',
          label: 'JD Edwards',
          link: {type: 'generated-index', slug: '/liberty/nomasx-1/settings/jde', description: 'JDE-specific licensing catalog: system codes, reclassification, prerequisites, restrictions.'},
          items: [
            'liberty/nomasx1/settings/jde/system-code',
            'liberty/nomasx1/settings/jde/reclassification',
            'liberty/nomasx1/settings/jde/prerequisite',
            'liberty/nomasx1/settings/jde/restrictions',
          ],
        },
        {
          type: 'category',
          label: 'Oracle',
          link: {type: 'generated-index', slug: '/liberty/nomasx-1/settings/oracle', description: 'Oracle catalog: versions, options, features.'},
          items: [
            'liberty/nomasx1/settings/oracle/versions',
            'liberty/nomasx1/settings/oracle/options',
            'liberty/nomasx1/settings/oracle/features',
          ],
        },
        {
          type: 'category',
          label: 'Pricing',
          link: {type: 'generated-index', slug: '/liberty/nomasx-1/settings/pricing', description: 'Component catalog, licensing metrics and price book.'},
          items: [
            'liberty/nomasx1/settings/pricing/components',
            'liberty/nomasx1/settings/pricing/metrics',
            'liberty/nomasx1/settings/pricing/pricing',
          ],
        },
      ],
    },
  ],

  nomajdeSidebar: [
    'liberty/nomajde/overview',
    {
      type: 'category',
      label: 'Master Data',
      items: [
        'liberty/nomajde/master-data/udc-types',
        'liberty/nomajde/master-data/udc-codes',
      ],
    },
    {
      type: 'category',
      label: 'Security Maintenance',
      items: [
        'liberty/nomajde/security-maintenance/user-management',
        'liberty/nomajde/security-maintenance/role-management',
        'liberty/nomajde/security-maintenance/role-relationships',
        'liberty/nomajde/security-maintenance/environments',
        'liberty/nomajde/security-maintenance/security-workbench',
      ],
    },
  ],

  nomaublSidebar: [
    'nomaubl/getting-started',
    {
      type: 'category',
      label: 'Application',
      link: {type: 'generated-index', slug: '/nomaubl/application', description: 'Main app navigation: dashboard, tech dashboard, invoices, e-reporting, e-directory, VAT declaration, integration errors, notifications and AI capabilities.'},
      items: [
        'nomaubl/application/dashboard',
        'nomaubl/application/tech-dashboard',
        'nomaubl/application/invoices',
        'nomaubl/application/ereporting',
        'nomaubl/application/edirectory',
        'nomaubl/application/vat-declaration',
        'nomaubl/application/integration-errors',
        'nomaubl/application/notifications',
        'nomaubl/application/ai-capabilities',
      ],
    },
    {
      type: 'category',
      label: 'Sync',
      link: {type: 'generated-index', slug: '/nomaubl/sync', description: 'Inbound/outbound synchronisation: fetch input, import and retrieve statuses.'},
      items: [
        'nomaubl/sync/fetch-input',
        'nomaubl/sync/import',
        'nomaubl/sync/retrieve-statuses',
      ],
    },
    {
      type: 'category',
      label: 'Processing',
      link: {type: 'generated-index', slug: '/nomaubl/processing', description: 'Single document-processing entry point (XML or UBL, selected by the template), the chained Extract and Process flow, and the API connector tester.'},
      items: [
        'nomaubl/processing/document',
        'nomaubl/processing/extract-and-process',
        'nomaubl/processing/process-api',
      ],
    },
    {
      type: 'category',
      label: 'UBL Tools',
      link: {type: 'generated-index', slug: '/nomaubl/ubl-tools', description: 'Validate, edit and inspect UBL/XML; manage UBL defaults.'},
      items: [
        'nomaubl/ubl-tools/validate',
        'nomaubl/ubl-tools/xsl-editor',
        'nomaubl/ubl-tools/xml-viewer',
        {
          type: 'category',
          label: 'UBL Defaults',
          link: {type: 'generated-index', slug: '/nomaubl/ubl-tools/ubl-defaults', description: 'Default values applied to generated UBL documents and how to override them per template.'},
          items: [
            'nomaubl/ubl-tools/ubl-defaults/overview',
            'nomaubl/ubl-tools/ubl-defaults/ubl-header-defaults',
            'nomaubl/ubl-tools/ubl-defaults/scheme-ids',
            'nomaubl/ubl-tools/ubl-defaults/invoice-type',
            'nomaubl/ubl-tools/ubl-defaults/business-process-type',
            'nomaubl/ubl-tools/ubl-defaults/payment-code-mapping',
            'nomaubl/ubl-tools/ubl-defaults/unit-of-measure-mapping',
            'nomaubl/ubl-tools/ubl-defaults/currency-code-mapping',
            'nomaubl/ubl-tools/ubl-defaults/document-type-bar-routing',
            'nomaubl/ubl-tools/ubl-defaults/vat-categories',
            'nomaubl/ubl-tools/ubl-defaults/suppliers-companies',
            'nomaubl/ubl-tools/ubl-defaults/french-legal-notes',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Extract',
      link: {type: 'generated-index', slug: '/nomaubl/extract', description: 'Source extraction channels: archive directories, FTP/SFTP servers and JD Edwards BIP Print Queue.'},
      items: [
        'nomaubl/extract/extract-archive',
        'nomaubl/extract/extract-ftp',
        'nomaubl/extract/extract-bip',
      ],
    },
    {
      type: 'category',
      label: 'Management',
      link: {type: 'generated-index', slug: '/nomaubl/management', description: 'Operational management: document templates, PDF templates, action bindings, notification rules, file versions, processing log and the command-line interface.'},
      items: [
        'nomaubl/management/documents',
        'nomaubl/management/pdf-templates',
        'nomaubl/management/actions',
        'nomaubl/management/notification-rules',
        'nomaubl/management/file-versions',
        'nomaubl/management/processing-log',
        'nomaubl/management/command-line',
      ],
    },
    {
      type: 'category',
      label: 'Configuration',
      link: {type: 'generated-index', slug: '/nomaubl/configuration', description: 'Application-wide configuration: system parameters, reference lists, connectors and security.'},
      items: [
        {
          type: 'category',
          label: 'System',
          link: {type: 'generated-index', slug: '/nomaubl/configuration/system', description: 'System-level parameters: e-directory, e-invoicing, fetch invoices, document types and statuses.'},
          items: [
            'nomaubl/configuration/system/edirectory',
            'nomaubl/configuration/system/einvoicing',
            'nomaubl/configuration/system/ereporting',
            'nomaubl/configuration/system/fetch-invoices',
            'nomaubl/configuration/system/global',
            'nomaubl/configuration/system/document-types',
            'nomaubl/configuration/system/statuses',
          ],
        },
        'nomaubl/configuration/reference-lists',
        'nomaubl/configuration/custom-lists',
        'nomaubl/configuration/list-views',
        'nomaubl/configuration/api-connectors',
        'nomaubl/configuration/sql-connectors',
        {
          type: 'category',
          label: 'Database Connectors',
          link: {type: 'generated-index', slug: '/nomaubl/configuration/database-connectors', description: 'Database connection settings for NomaUBL and JD Edwards.'},
          items: [
            'nomaubl/configuration/database-connectors/nomaubl',
            'nomaubl/configuration/database-connectors/jdedwards',
          ],
        },
        'nomaubl/configuration/ftp-connectors',
        {
          type: 'category',
          label: 'Security',
          link: {type: 'generated-index', slug: '/nomaubl/configuration/security', description: 'Users and roles management.'},
          items: [
            'nomaubl/configuration/security/users',
            'nomaubl/configuration/security/roles',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'References',
      link: {type: 'generated-index', slug: '/nomaubl/references', description: 'Reference docs surfaced inside the app: status codes, reason codes, UBL semantics, database schema and HTTP API.'},
      items: [
        'nomaubl/references/status-reference',
        'nomaubl/references/reason-codes',
        'nomaubl/references/ubl-reference',
        'nomaubl/references/database-tables',
        {
          type: 'link',
          label: 'API Reference',
          href: '/nomaubl/api-reference/',
        },
      ],
    },
    'nomaubl/release-notes',
  ],

  apiSidebar: [
    'api/getting-started',
    {
      type: 'category',
      label: 'JD Edwards API',
      link: {type: 'generated-index', slug: '/api/jd-edwards-api', description: 'Java packages for JD Edwards integration: BLOB exports for BI Publisher and BSFN source code.'},
      items: [
        'api/jde-api/jdebip',
        'api/jde-api/jdebsfn',
      ],
    },
    {
      type: 'category',
      label: 'BI Publisher API',
      link: {type: 'generated-index', slug: '/api/bi-publisher-api', description: 'BI Publisher integration utilities: Code 128 barcodes and the NOMABIP wrapper API.'},
      items: [
        'api/bip-api/nomabc',
        'api/bip-api/nomabip',
      ],
    },
  ],
};

export default sidebars;
